# Permalinks
permalink:           /blog/:title/

# Setup
title:               Collegiate Entrepreneurs Organisation, Delhi University
tagline:             CEO DU - Collegiate Entrepreneurs Organization, Delhi University (DU)
description:         We Breathe Startups
footer:              CEO, Delhi University

exclude:             [/psd/]


# Markdown



# SASS
sass:
  sass_dir:          _sass
  style:            compressed
  encoding:          utf-8

# Google Analytics
analytics_id:  


# SEO
author:
  name: Shivansh Mehendiratta
  twitter: ceodu
  instagram: ceo_du
  youtube: ceodu
  email: ceoinfo.du@gmail.com

defaults:
  - scope:
      path: ""
    values:
      image: /bg.jpeg


profile: /bg.jpg

twitter:
  username: shivansh3121

social:
  name: Shivansh Mehendiratta
  links:
    - https://twitter.com/shivansh3121
    - https://instagram.com/ceo_du
    - https://youtube.com/c/shivansh3121

# Gems
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-pdf-embed
